name: Price Checker

on:
  schedule:
    - cron: "0 */2 * * *"   # every 2 hours
  workflow_dispatch:        # allows manual run button

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install scrapy

      - name: Run Scrapy spider
        run: |
          cd pricecrawler
          scrapy crawl amazon_price -a asin=B0895DY6F5 -O result.json

      - name: Commit updated result
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add pricecrawler/result.json
          git commit -m "Automated price update" || echo "No changes"
          git push
